server:
  port: 8761

spring:
  application:
    name: ef-service-registry

ef:
  serviceRegistry:
    username: serviceregistry
    password: vento123
  easyfinancesBack:
    username: efeasyfinancesback
    password: vento123

eureka:
  client:
    service-url:
      defaultZone: 'http://${ef.serviceRegistry.username}:${ef.serviceRegistry.password}@localhost:8761/eureka'
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF